services:
  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  plant-coach-weather-api:
    image: jmgrant/plant-coach-weather-api-dev:latest
    command: "./bin/rails server -p 3001"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - OPEN_WEATHER_API_KEY=${OPEN_WEATHER_API_KEY}
      - RAILS_MASTER_KEY=${WEATHER_API_MASTER_KEY}
    network_mode: service:plant-coach-be-web

  plant-coach-be-web:
    build: .
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - PLANT_COACH_WEATHER_API_BASE_URL=http://localhost:3001
    volumes:
      - app-storage:/rails/storage
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  postgres_data: {}
  app-storage: {}
  