name: Deploy

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Prepare Kubeconfig
        run: |
          mkdir /home/runner/.kube
          touch /home/runner/.kube/config
          echo "${{ secrets.KUBECONFIG }}" > /home/runner/.kube/config
      -
        name: Deploy Service
        run: |
          helm repo add plant-coach-be "https://github.com/Plant-Coach/plant-coach-helm"
          helm upgrade --install --set-json='imagePullSecrets=[{"name": "${{ secrets.SECRET_NAME }}"}]' --set-json='env_variables=[{"name": "RAILS_ENV", "value": "${{ secrets.RAILS_ENV }}"}, {"name": "RAILS_MASTER_KEY", "value": "${{ secrets.RAILS_MASTER_KEY }}"}, {"name": "POSTGRES_PORT", "value": "${{ secrets.POSTGRES_PORT }}"}, {"name": "POSTGRES_DB", "value": "${{ secrets.POSTGRES_DB }}"}, {"name": "POSTGRES_HOST", "value": "${{ secrets.POSTGRES_HOST }}"}, {"name": "POSTGRES_USER", "value": "${{ secrets.POSTGRES_USER }}"}, {"name": "POSTGRES_PASSWORD", "value": "${{ secrets.POSTGRES_PASSWORD }}"}]' plant-coach-be . --kube-context ${{ secrets.KUBE_CONTEXT }}