name: Deploy/Release Chart

on:
  push:
  # workflow_run:
  #   workflows:
  #     - "Build and Push"
  #   branches:
  #     - main
  #   types:
  #     - completed

jobs:
  deploy:
    environment: production
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Add Kubeconfig
        run: |
          mkdir /home/runner/.kube
          touch /home/runner/.kube/config
          echo "${{ secrets.KUBECONFIG }}" > /home/runner/.kube/config

      - name: Deploy Chart
        run: |
          helm upgrade --install --set fullnameOverride=plant-coach-be --set serviceAccount.name=plant-coach-be --set image.repository=jmgrant/plant-coach-be:amd64-${{ github.sha }} --set-json='imagePullSecrets=[{"name": "${{ secrets.SECRET_NAME }}"}]' --set-json='env_variables=[{"name": "HELM_CHART", "value": "${{ secrets.HELM_CHART }}"}, {"name": "RAILS_ENV", "value": "${{ secrets.RAILS_ENV }}"}, {"name": "RAILS_MASTER_KEY", "value": "${{ secrets.RAILS_MASTER_KEY }}"}, {"name": "POSTGRES_PORT", "value": "${{ secrets.POSTGRES_PORT }}"}, {"name": "POSTGRES_DB", "value": "${{ secrets.POSTGRES_DB }}"}, {"name": "POSTGRES_HOST", "value": "${{ secrets.POSTGRES_HOST }}"}, {"name": "POSTGRES_USER", "value": "${{ secrets.POSTGRES_USER }}"}, {"name": "POSTGRES_PASSWORD", "value": "${{ secrets.POSTGRES_PASSWORD }}"}, {"name": "PLANT_COACH_WEATHER_API_BASE_URL", "value": "${{ secrets.PLANT_COACH_WEATHER_API_BASE_URL }}"}]' plant-coach-be ${{ secrets.HELM_CHART }} -n plant-coach-production \
          --kube-context "$KUBE_CONTEXT" \
          --username joel-grant \
          --password ${{ secrets.CLOUDSMITH_API_KEY }}