name: Test and Lint
on:
  push:
    # branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      PLANT_COACH_WEATHER_API_BASE_URL: ${{ secrets.WEATHER_API_BASE_URL}}
    services:
      postgres:
        image: postgres:14.12-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
      plant-coach-weather-api:
        image: jmgrant/plant-coach-weather-api:latest
        ports:
          - 3000:80
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.234.0
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1.234.0
        with:
          bundler-cache: true
      - name: Resolve bundler with binstubs
        run: bundle binstubs bundler --force
      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop
      # Add or replace any other lints here
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman -q -w2
        # ToDo: Turn back on
      # - name: Lint Ruby files
      #   run: bin/rubocop --parallel
    
  ruby-critic:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          
      - name: Fetch all branches
        run: git fetch

      - name: Run RubyCritic
        if: github.ref != 'refs/heads/main'
        run: |
          bundle exec rubycritic --mode-ci --no-browser

      - name: Upload RubyCritic report
        if: always() && github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: rubycritic-report
          path: tmp/rubycritic

      - name: Deploy RubyCritic report to GitHub Pages
        if: always() && github.ref != 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tmp/rubycritic
          publish_branch: gh-pages
      
      - name: View Job Output
        if: always()
        run: |
          echo "View Report: https://plant-coach.github.io/joel-grant-be/compare/main/overview.html"